# **Testing**

In [2]:
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import pandas as pd

In [1]:
from sklearn.datasets import make_friedman2
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import DotProduct, WhiteKernel
X, y = make_friedman2(n_samples=500, noise=0, random_state=0)
kernel = DotProduct() + WhiteKernel()
gpr = GaussianProcessRegressor(kernel=kernel,
        random_state=0).fit(X, y)
gpr.score(X, y)
gpr.predict(X[:2,:], return_std=True)

c:\Users\evanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\gaussian_process\kernels.py:445: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__sigma_0 is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
c:\Users\evanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\gaussian_process\kernels.py:455: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(


(array([653.08792288, 592.16905327]), array([316.68016218, 316.65121679]))

In [2]:
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import pandas as pd
avo_TRAIN = pd.read_csv('dataset(small).csv', index_col='ID')
# View the data!
avo_TRAIN.head()
#avo_TRAIN.describe()

# Clean Data

avo_TRAIN = avo_TRAIN.dropna(axis=0)

features = ["Population","Land size","Working hours","Corruption","Environment","Income","Cost of living","N recreational buildings","N office buildings","N essential buildings","N residential buildings"]

X = avo_TRAIN[features]
y = avo_TRAIN.Happiness
from sklearn import *

clf = LinearDiscriminantAnalysis()
clf.fit(X.to_numpy(), y.to_numpy())

TEST = pd.read_csv('dataset(test).csv', index_col='ID')

XforPredictions = TEST[features]
# Make Predictions!
yPredictions = clf.predict(XforPredictions)
print("Predictions:", yPredictions)
# Save to CSV File!

Predictions: [70 70 65 80 85 70 70 70 80 80 80]


c:\Users\evanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LinearDiscriminantAnalysis was fitted without feature names
  warnings.warn(


In [3]:
# load csvs
import pandas as pd
avo_TRAIN = pd.read_csv('dataset(small).csv', index_col='ID')
# View the data!
avo_TRAIN.head()
#avo_TRAIN.describe()

# Clean Data

# Drops missing values 
avo_TRAIN = avo_TRAIN.dropna(axis=0)


# Read more advanced ways to clean data
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html
# https://stackoverflow.com/questions/24458645/label-encoding-across-multiple-columns-in-scikit-learn
# Select data for learning
features = ["Population","Land size","Working hours","Corruption","Environment","Income","Cost of living","N recreational buildings","N office buildings","N essential buildings","N residential buildings"]

X = avo_TRAIN[features]
y = avo_TRAIN.Happiness
X.head()
#y.head()
# Regression Time!
# Sci Kit Learn! Scientific Computing library for python
from sklearn import *
# Pick the regression model we want to use

# Decision Tree Regression
# https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html
# model = tree.DecisionTreeRegressor(random_state=2020)

# Random Forest Regression
# https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html
model = ensemble.RandomForestRegressor(random_state=2024, n_estimators=200)
# Split training into some for training and some for testing
Xtrain, Xtest, ytrain, ytest = model_selection.train_test_split(X, y, test_size=0.1)

print("training split: ", len(Xtrain), "; test split: ", len(Xtest))
# Perform regression on the data
model.fit(X, y)
model.score(Xtest, ytest)
# Predict for Testing data
# Clean Data


# Read more advanced ways to clean data
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html
# https://stackoverflow.com/questions/24458645/label-encoding-across-multiple-columns-in-scikit-learn
# Select features
TEST = pd.read_csv('dataset(test).csv', index_col='ID')

XforPredictions = TEST[features]
# Make Predictions!
yPredictions = model.predict(XforPredictions)
print("Predictions:", yPredictions)
# Save to CSV File!

training split:  9 ; test split:  2
Predictions: [71.075 70.95  69.275 79.875 81.55  71.075 70.8   76.175 79.45  78.1
 78.375]


In [4]:
import fitting

TEST = pd.read_csv('dataset(test).csv', index_col='ID')

features = ["Population","Land size","Working hours","Corruption","Environment","Income","Cost of living","N recreational buildings","N office buildings","N essential buildings","N residential buildings"]
XforPredictions = TEST[features]

fitting.main(XforPredictions)

c:\Users\evanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LinearDiscriminantAnalysis was fitted without feature names
  warnings.warn(


array([70, 70, 65, 80, 85, 70, 70, 70, 80, 80, 80], dtype=int64)

In [11]:
import scipy as sp
from scipy.optimize import LinearConstraint
from scipy.optimize import minimize

import fitting


def f(x):
    import numpy as np

    #offset = np.random.normal(0, 10, 4)
    #parameters = np.array([x1,x2,x3,x4]) + offset
    
    c1, c2, c3, c4, c5, c6, c7 = CONSTANTS
    x1, x2, x3, x4 = x
    return -1*MODEL.predict(np.array([c1, c2, c3, c4, c5, c6, c7, x1, x2, x3, x4]).reshape(1,-1))


global CONSTANTS
CONSTANTS = [2.7,223,31.6,2,6,96000,83600]

global MODEL
MODEL = fitting.main()


buildings_max = CONSTANTS[1]/0.01
print(buildings_max)

#cons = ({'type': 'ineq', 'fun': lambda x:  x[0] - 2 * x[1] + 2},
#    {'type': 'ineq', 'fun': lambda x: -x[0] - 2 * x[1] + 6},
#    {'type': 'ineq', 'fun': lambda x: -x[0] - 2 * x[1] + 6},
#    {'type': 'ineq', 'fun': lambda x: -x[0] + 2 * x[1] + 2})
cons = ()
    
bnds = ((1, buildings_max), (1, buildings_max), (1, buildings_max), (1, buildings_max))

#minimize(f, [50, 50, 50, 50], bounds=bnds, constraints=cons, method='Nelder-Mead')
minimize(f, [50, 50, 50, 50], method='BFGS', options={'gtol': 1e-100, 'disp': True})

22300.0
Optimization terminated successfully.
         Current function value: -80.750000
         Iterations: 0
         Function evaluations: 5
         Gradient evaluations: 1


c:\Users\evanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\evanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\evanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\evanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\evanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid fea

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: -80.75
        x: [ 5.000e+01  5.000e+01  5.000e+01  5.000e+01]
      nit: 0
      jac: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 hess_inv: [[1 0 0 0]
            [0 1 0 0]
            [0 0 1 0]
            [0 0 0 1]]
     nfev: 5
     njev: 1